### ISSUE TITLE
Could Not Load File During Patching. 

### ISSUE THREAD

**Issue by titanbass1** [tr4wzified/AOSISCSoundPatcher#15]
Hello, I just updated to the latest version and received the following error: 

Running patch.
Reading settings: C:\Modding\Synthesis\Data\Skyrim Special Edition\AOSISCSoundPatcher\settings.json
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Newtonsoft.Json.JsonSerializer.ApplySerializerSettings(JsonSerializer serializer, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Mutagen.Bethesda.Synthesis.Internal.ReflectionSettingsTarget`1.Get()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AOSISCSoundPatcher.Program.RunPatch(IPatcherState`2 state)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0`2.<<AddPatch>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext()

I tried clearing the files and reinstalling, but this still persisted. Let me know if you need anymore information.

**Comment by HellKnightX88** [comment]
Running into the same issue as of today.

**Comment by Magink666** [comment]
same here

**Comment by Magink666** [comment]
![image](https://user-images.githubusercontent.com/128214221/226092013-5870ad85-334e-4152-9e7e-7326a1f4bd9f.png)
Could you fix it? Would be greatly appreciated.

**Comment by tr4wzified** [comment]
Not sure what this is suddenly caused by, but looking over at the Synthesis Discord someone fixed it by removing the settings. Waiting on response from Noggog to see if I can do something about this directly or whether it's a Synthesis thing 
![image](https://user-images.githubusercontent.com/55751269/226096369-3873c4e3-035b-4021-8ce0-dbad4ec5cec6.png)

**Comment by tr4wzified** [comment]
Caused by .NET 7.0.4, try installing .NET 7.0.3 to fix the issue.

**Comment by tr4wzified** [comment]
![afbeelding](https://user-images.githubusercontent.com/55751269/226166664-d2d6f7d6-31a6-471a-b958-18b9cb6aa872.png)
