### ISSUE TITLE
Error when running patcher

### ISSUE THREAD

**Issue by 3039373** [tr4wzified/AOSISCSoundPatcher#17]
I got this error when running a patcher. 
Don't know what's wrong because other patchers are working well except this one.

Compiling
("C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Git\5uuur21b.tob\Runner\AOSISCSoundPatcher"): "dotnet" "build \"AOSISCSoundPatcher.csproj\" --runtime win-x64 -c Release"
No extra data to consider
Compiled
Sha "2a8cba261ed435c16750b2c322ff2f8db1461e3d"
Running
(""): "dotnet" "run --project \"C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Git\5uuur21b.tob\Runner\AOSISCSoundPatcher\AOSISCSoundPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"C:\Program Files (x86)\Steam\Aurora_1.0_RC_4a\Tools\Synthesis 0.25.3\Data\Skyrim Special Edition\AOSISCSoundPatcher\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Workspace\Synthesis\1 - AOSISCSoundPatcher\Synthesis.esp\" --PatcherName AOSISCSoundPatcher"
Mutagen version: 0.40
Mutagen sha: 2c78952371b3e1019cbe76584ebd9d755411c751
Synthesis version: 0.25.3
Synthesis sha: 4c420cd866298eed968c3ac5bb39796eeab06365
Newtonsoft version: 13.0.1+ae9fe44e1323e91bcbd185ca1a14099fba7c021f
run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Program Files (x86)\Steam\Aurora_1.0_RC_4a\Tools\Synthesis 0.25.3\Data\Skyrim Special Edition\AOSISCSoundPatcher" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\tldgk\AppData\Local\Temp\Synthesis\cjd42dys.ep2\Workspace\Synthesis\1 - AOSISCSoundPatcher\Synthesis.esp" --PatcherName AOSISCSoundPatcher
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
Reading settings: C:\Program Files (x86)\Steam\Aurora_1.0_RC_4a\Tools\Synthesis 0.25.3\Data\Skyrim Special Edition\AOSISCSoundPatcher\settings.json
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 吏?뺣맂 ?뚯씪??李얠쓣 ???놁뒿?덈떎.
File name: 'System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Newtonsoft.Json.JsonSerializer.ApplySerializerSettings(JsonSerializer serializer, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Mutagen.Bethesda.Synthesis.Internal.ReflectionSettingsTarget`1.Get()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AOSISCSoundPatcher.Program.RunPatch(IPatcherState`2 state)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass15_0`2.<<AddPatch>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext()

**Comment by tr4wzified** [comment]
Lots of people having issues after the .NET 7 upgrade, should be fixed by the SDK but Microsoft pushed out a few bad updates lately. Downgraded back to .NET 6, let me know if it's fixed now.

**Comment by 3039373** [comment]
Patcher succesfully done with .NET 6, but I don't think it's working. Synthesis.esp is enabled,  Heavy armor footsteps still sounds like light armor (Armor added by mods).

**Comment by tr4wzified** [comment]
Can you check the records in xEdit, how do they look?

**Comment by 3039373** [comment]
nvm my friend, it was my mistake, I checked armors in my game it works perfectly. thank you for help !
